name: Build go binary

on:
  push:
    branches: [ "mojo" ]
  pull_request:
    branches: [ "mojo" ]

jobs:
  build:
    name: build and store artifacts etc
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: install deps
      run: go get && go install
    
    - name: Build main file
      run: go build main.go
    
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: vortexus_linux_bin
        path: ./main

